-- edw_prod_dbo.dm_shipping_v source

CREATE OR REPLACE VIEW edw_prod_dbo.dm_shipping_v
AS SELECT f.source_system,
    f.org_id,
    f.delivery_id,
    f.delivery_detail_id,
    f.sold_to_contact_id,
    f.ship_to_contact_id,
    f.bill_to_contact_id,
    f.customer_id,
    f.move_order_line_id,
    f.ship_from_location_id,
    f.ship_to_location_id,
    f.ship_to_site_use_id,
    f.deliver_to_location_id,
    f.delivery_to_site_use_id,
    f.currency_code AS shipment_currency,
    f.delivery_number,
    f.delivery_status_code,
    f.delivery_status,
    f.source_header_type_name,
    f.shipment_number,
    f.ship_date,
    f.carrier,
    f.freight_terms_code,
    f.fob_code,
    f.waybill,
    f.subinventory,
    f.lot_number,
    f.serial_number,
    f.revision,
    f.released_status,
    f.date_requested,
    f.date_scheduled,
    f.packing_instructions,
    f.tracking_number,
    f.cust_po_number,
    sof.unit_price,
    f.requested_quantity,
    f.shipped_quantity,
    f.delivered_quantity,
    f.cancelled_quantity,
    f.picked_quantity,
    f.confirm_date,
    f.picked_date,
    f.tp_item_number,
    so.header_id,
    so.line_id AS line_id_w_sales_orders_d,
    so.order_number,
    so.life_cycle_status,
    so.order_header_type,
    so.order_status,
    so.order_currency,
    so.hold_type,
    so.customer_po,
    so.order_source,
    so.order_source_reference,
    so.repair_type::character varying(30) AS service_activity,
    so.service_agreement_number,
    so.service_agreement_description,
    so.order_date,
    so.order_creation_date,
    so.order_created_by,
    so.booked_date,
    so.backlog_date,
    so.bill_only_ship_date,
    so.request_date,
    so.promise_date,
    so.schedule_date,
    so.actual_ship_date,
    so.fulfillment_date,
    so.actual_fulfillment_date,
    so.latest_acceptable_date,
    so.booked_flag,
    so.cancelled_flag,
    so.fulfilled_flag,
    so.line_number,
    so.line_status,
    so.line_category,
    so.line_type,
    so.line_type_name,
    so.price_list,
    so.price_override,
    so.product_class,
    so.classification,
    so.shipment_number AS order_shipment_number,
    so.ordered_item,
    so.item_type_code,
    so.modifier_name,
    so.repair_type,
    so.return_reason_code,
    so.subinventory AS order_subinventory,
    so.tax_code,
    so.tax_date,
    so.tax_excempt_flag,
    so.sales_account,
    so.mktg_account_rule,
    so.mktg_channel,
    so.open_flag,
    so.pricing_date,
    so.shippable_flag,
    so.calc_price_flag,
    so.fob_point_code,
    so.freight_carrier_code,
    so.mktg_product_channel,
    so.tax_point_code,
    so.schedule_status_code,
    so.shipment_priority_code,
    so.price_request_code,
    so.shipping_method_code,
    so.order_uom,
    so.pricing_uom,
    so.source_type,
    so.line_creation_date,
    so.line_created_by,
    so.inv_trx_number,
    so.inv_trx_date,
    so.inv_trx_rate_type,
    so.inv_exch_date,
    so.inv_exch_rate,
    so.inv_gl_date,
    so.inv_currency_code,
    so.ic_po_number,
    so.ic_po_line,
    so.ref_order_number,
    so.ref_order_line,
    so.plan_date,
    so.ebs_line_id,
    so.fulfillment_line_number,
    so.customer_pn,
    ou.ou_code,
    ou.ou_name,
    st.site_use_id AS st_site_use_id,
    st.customer_account AS st_customer_account,
    st.customer_name AS st_customer_name,
    st.account_name AS st_account_name,
    st.customer_class_code AS st_customer_class_code,
    st.semi_non_semi AS st_semi_non_semi,
    st.site_use_code AS st_site_use_code,
    st.site_number AS st_site_number,
    st.site_name AS st_site_name,
    st.address_1 AS st_address_1,
    st.address_2 AS st_address_2,
    st.address_3 AS st_address_3,
    st.address_4 AS st_address_4,
    st.city AS st_city,
    st.state AS st_state,
    st.postal_code AS st_postal_code,
    st.site_country AS st_country,
    st.region AS st_region,
    st.territory AS st_territory,
    st.channel AS st_channel,
    st.location AS st_location,
    st.primary_flag AS st_primary_flag,
    st.status AS st_status,
    st.primary_market_segment AS st_primary_market_segment,
    st.secondary_market_segment AS st_secondary_market_segment,
    st.party_id AS st_party_id,
    st.party_number AS st_party_number,
    st.party_type AS st_party_type,
    st.cust_account_id AS st_cust_account_id,
    st.account_status AS st_account_status,
    st.site_status AS st_site_status,
    sld.cust_account_id AS sold_cust_account_id,
    sld.customer_account AS sold_customer_account,
    sld.customer_name AS sold_customer_name,
    sld.account_name AS sold_account_name,
    sld.customer_class_code AS sold_customer_class_code,
    sld.semi_non_semi AS sold_semi_non_semi,
    sld.region AS sold_region,
    org.org_code AS inv_org_code,
    org.org_name AS inv_org_name,
    org.org_type AS inv_org_type,
    org.region AS inv_org_region,
    org.src_org_id AS inv_org_id,
    i.inventory_item_id,
    i.organization_id,
    i.organization_code,
    i.item_number,
    i.description,
    i.buyer_id,
    i.buyer_name,
    i.planner_code,
    i.planner_name,
    i.item_type,
    i.inventory_item_status_code,
    i.inventory_planning_code,
    i.sales_account AS item_sales_account,
    i.cost_of_sales_account AS item_cost_of_sales_account,
    i.expense_account AS item_expense_account,
    i.atp_flag,
    i.atp_rule_id,
    i.build_in_wip_flag,
    i.check_shortages_flag,
    i.customer_order_enabled_flag,
    i.customer_order_flag,
    i.internal_order_enabled_flag,
    i.internal_order_flag,
    i.inventory_asset_flag,
    i.inventory_item_flag,
    i.outside_operation_flag,
    i.purchasing_enabled_flag,
    i.returnable_flag,
    i.service_item_flag,
    i.serviceable_product_flag,
    i.shippable_item_flag,
    i.so_transactions_flag,
    i.item_standard_cost,
    i.standard_cost_currency,
    i.item_standard_cost_usd,
    i.lead_time_lot_size,
    i.fixed_lead_time,
    i.full_lead_time,
    i.postprocessing_lead_time,
    i.preprocessing_lead_time,
    i.cum_manufacturing_lead_time,
    i.cumulative_total_lead_time,
    i.variable_lead_time,
    i.fixed_days_supply,
    i.fixed_lot_multiplier,
    i.fixed_order_quantity,
    i.reservable_type,
    i.wip_supply_type,
    i.planning_make_buy_code,
    i.primary_uom_code,
    i.primary_unit_of_measure,
    i.unit_height,
    i.unit_length,
    i.unit_of_issue,
    i.unit_volume,
    i.unit_weight,
    i.unit_width,
    i.volume_uom_code,
    i.weight_uom_code,
    i.hts_code,
    i.product_family,
    i.product_line,
    i.product_model,
    i.commodity_class,
    i.category,
    i.sourcing_segment,
    i.atp_rule_name,
    i.item_creation_date,
    i.country_of_origin,
    sof.product_code_node,
    fh."LEVEL05_NAME" AS product_code_label,
    fh.level01_name AS segment_l1,
    fh.level03_name AS family_segment_l3,
    fh.level02_name AS product_segment_l2,
    fh.level04_name AS family_group_l4,
    i.material_cost_usd,
    i.item_standard_cost AS item_standard_cost_lc
   FROM edw_prod_dbo.w_shipping_f f
     JOIN edw_prod_dbo.w_sales_orders_d so ON f.so_line_id = so.line_id AND f.source_system::text = so.source_system::text
     JOIN edw_prod_dbo.w_sales_orders_f sof ON sof.line_id = so.line_id AND sof.source_system::text = so.source_system::text
     JOIN edw_prod_dbo.w_oper_unit_d ou ON f.org_id = ou.org_id AND f.source_system::text = ou.source_system::text
     LEFT JOIN edw_prod_dbo.w_customer_site_d st ON f.ship_to_site_use_id = st.site_use_id AND f.source_system::text = st.source_system::text
     LEFT JOIN edw_prod_dbo.w_customer_d sld ON f.customer_id = sld.cust_account_id AND f.source_system::text = sld.source_system::text
     JOIN edw_prod_dbo.w_organization_d org ON f.organization_id = org.src_org_id AND f.source_system::text = org.source_system::text
     JOIN edw_prod_dbo.w_item_org_d i ON f.inventory_item_id = i.inventory_item_id AND f.organization_id = i.organization_id AND f.source_system::text = i.source_system::text
     LEFT JOIN edw_prod_dbo."W_PRODUCT_DH_V" fh ON sof.product_code_node::text = fh.node::text
  WHERE so.order_header_type::text <> 'Transfer Order'::text
UNION ALL
 SELECT f.source_system,
    f.org_id,
    f.delivery_id,
    f.delivery_detail_id,
    f.sold_to_contact_id,
    f.ship_to_contact_id,
    f.bill_to_contact_id,
    f.customer_id,
    f.move_order_line_id,
    f.ship_from_location_id,
    f.ship_to_location_id,
    f.ship_to_site_use_id,
    f.deliver_to_location_id,
    f.delivery_to_site_use_id,
    f.currency_code AS shipment_currency,
    f.delivery_number,
    f.delivery_status_code,
    f.delivery_status,
    f.source_header_type_name,
    f.shipment_number,
    f.ship_date,
    f.carrier,
    f.freight_terms_code,
    f.fob_code,
    f.waybill,
    f.subinventory,
    f.lot_number,
    f.serial_number,
    f.revision,
    f.released_status,
    f.date_requested,
    f.date_scheduled,
    f.packing_instructions,
    f.tracking_number,
    f.cust_po_number,
    sof.unit_price,
    f.requested_quantity,
    f.shipped_quantity,
    f.delivered_quantity,
    f.cancelled_quantity,
    f.picked_quantity,
    f.confirm_date,
    f.picked_date,
    f.tp_item_number,
    so.header_id,
    so.line_id AS line_id_w_sales_orders_d,
    so.order_number,
    so.life_cycle_status,
    so.order_header_type,
    so.order_status,
    so.order_currency,
    so.hold_type,
    so.customer_po,
    so.order_source,
    so.order_source_reference,
    so.repair_type::character varying(30) AS service_activity,
    so.service_agreement_number,
    so.service_agreement_description,
    so.order_date,
    so.order_creation_date,
    so.order_created_by,
    so.booked_date,
    so.backlog_date,
    so.bill_only_ship_date,
    so.request_date,
    so.promise_date,
    so.schedule_date,
    so.actual_ship_date,
    so.fulfillment_date,
    so.actual_fulfillment_date,
    so.latest_acceptable_date,
    so.booked_flag,
    so.cancelled_flag,
    so.fulfilled_flag,
    so.line_number,
    so.line_status,
    so.line_category,
    so.line_type,
    so.line_type_name,
    so.price_list,
    so.price_override,
    so.product_class,
    so.classification,
    so.shipment_number AS order_shipment_number,
    so.ordered_item,
    so.item_type_code,
    so.modifier_name,
    so.repair_type,
    so.return_reason_code,
    so.subinventory AS order_subinventory,
    so.tax_code,
    so.tax_date,
    so.tax_excempt_flag,
    so.sales_account,
    so.mktg_account_rule,
    so.mktg_channel,
    so.open_flag,
    so.pricing_date,
    so.shippable_flag,
    so.calc_price_flag,
    so.fob_point_code,
    so.freight_carrier_code,
    so.mktg_product_channel,
    so.tax_point_code,
    so.schedule_status_code,
    so.shipment_priority_code,
    so.price_request_code,
    so.shipping_method_code,
    so.order_uom,
    so.pricing_uom,
    so.source_type,
    so.line_creation_date,
    so.line_created_by,
    so.inv_trx_number,
    so.inv_trx_date,
    so.inv_trx_rate_type,
    so.inv_exch_date,
    so.inv_exch_rate,
    so.inv_gl_date,
    so.inv_currency_code,
    so.ic_po_number,
    so.ic_po_line,
    so.ref_order_number,
    so.ref_order_line,
    so.plan_date,
    so.ebs_line_id,
    so.fulfillment_line_number,
    so.customer_pn,
    ou.ou_code,
    ou.ou_name,
    st.location_id::numeric(30,0) AS st_site_use_id,
    sld.party_number::character varying(20) AS st_customer_account,
    sld.customer_name AS st_customer_name,
    sld.party_number::character varying(30) AS st_account_name,
    sld.customer_class_code AS st_customer_class_code,
    sld.semi_non_semi AS st_semi_non_semi,
    st.location_id::character varying(20) AS st_site_use_code,
    ''::character varying(30) AS st_site_number,
    st.description::character varying(120) AS st_site_name,
    st.address_line_1::character varying(100) AS st_address_1,
    st.address_line_2::character varying(100) AS st_address_2,
    st.address_line_3::character varying(100) AS st_address_3,
    st.address_line_4::character varying(100) AS st_address_4,
    st.town_or_city::character varying(30) AS st_city,
    st.region_2::character varying(30) AS st_state,
    st.postal_code::character varying(10) AS st_postal_code,
        CASE
            WHEN length(st.country::text) > 2 THEN st.ac_location_code::character varying(150)
            ELSE st.country::character varying(150)
        END AS st_country,
        CASE
            WHEN st.region_1::character varying(100) IS NULL OR st.region_2::character varying(100) IS NULL THEN st.region_3::character varying(100)
            WHEN st.region_2::character varying(100) IS NULL OR st.region_3::character varying(100) IS NULL THEN st.region_1::character varying(100)
            WHEN st.region_1::character varying(100) IS NULL OR st.region_3::character varying(100) IS NULL THEN st.region_2::character varying(100)
            ELSE NULL::character varying
        END::character varying(100) AS st_region,
    ''::character varying(100) AS st_territory,
    ''::character varying(10) AS st_channel,
    st.location_name::character varying(30) AS st_location,
    ''::character(1) AS st_primary_flag,
    st.active_status::character varying(20) AS st_status,
    ''::character varying(30) AS st_primary_market_segment,
    ''::character varying(30) AS st_secondary_market_segment,
    st.location_id::numeric(30,0) AS st_party_id,
    ''::character varying(30) AS st_party_number,
    ''::character varying(30) AS st_party_type,
    0::numeric(30,0) AS st_cust_account_id,
    st.active_status::character varying(30) AS st_account_status,
    st.active_status::character varying(10) AS st_site_status,
    sld.cust_account_id AS sold_cust_account_id,
    sld.customer_account AS sold_customer_account,
    sld.customer_name AS sold_customer_name,
    sld.account_name AS sold_account_name,
    sld.customer_class_code AS sold_customer_class_code,
    sld.semi_non_semi AS sold_semi_non_semi,
    sld.region AS sold_region,
    org.org_code AS inv_org_code,
    org.org_name AS inv_org_name,
    org.org_type AS inv_org_type,
    org.region AS inv_org_region,
    org.src_org_id AS inv_org_id,
    i.inventory_item_id,
    i.organization_id,
    i.organization_code,
    i.item_number,
    i.description,
    i.buyer_id,
    i.buyer_name,
    i.planner_code,
    i.planner_name,
    i.item_type,
    i.inventory_item_status_code,
    i.inventory_planning_code,
    i.sales_account AS item_sales_account,
    i.cost_of_sales_account AS item_cost_of_sales_account,
    i.expense_account AS item_expense_account,
    i.atp_flag,
    i.atp_rule_id,
    i.build_in_wip_flag,
    i.check_shortages_flag,
    i.customer_order_enabled_flag,
    i.customer_order_flag,
    i.internal_order_enabled_flag,
    i.internal_order_flag,
    i.inventory_asset_flag,
    i.inventory_item_flag,
    i.outside_operation_flag,
    i.purchasing_enabled_flag,
    i.returnable_flag,
    i.service_item_flag,
    i.serviceable_product_flag,
    i.shippable_item_flag,
    i.so_transactions_flag,
    i.item_standard_cost,
    i.standard_cost_currency,
    i.item_standard_cost_usd,
    i.lead_time_lot_size,
    i.fixed_lead_time,
    i.full_lead_time,
    i.postprocessing_lead_time,
    i.preprocessing_lead_time,
    i.cum_manufacturing_lead_time,
    i.cumulative_total_lead_time,
    i.variable_lead_time,
    i.fixed_days_supply,
    i.fixed_lot_multiplier,
    i.fixed_order_quantity,
    i.reservable_type,
    i.wip_supply_type,
    i.planning_make_buy_code,
    i.primary_uom_code,
    i.primary_unit_of_measure,
    i.unit_height,
    i.unit_length,
    i.unit_of_issue,
    i.unit_volume,
    i.unit_weight,
    i.unit_width,
    i.volume_uom_code,
    i.weight_uom_code,
    i.hts_code,
    i.product_family,
    i.product_line,
    i.product_model,
    i.commodity_class,
    i.category,
    i.sourcing_segment,
    i.atp_rule_name,
    i.item_creation_date,
    i.country_of_origin,
    sof.product_code_node,
    fh."LEVEL05_NAME" AS product_code_label,
    fh.level01_name AS segment_l1,
    fh.level03_name AS family_segment_l3,
    fh.level02_name AS product_segment_l2,
    fh.level04_name AS family_group_l4,
    i.material_cost_usd,
    i.item_standard_cost AS item_standard_cost_lc
   FROM edw_prod_dbo.w_shipping_f f
     JOIN edw_prod_dbo.w_sales_orders_d so ON f.so_line_id = so.line_id AND f.source_system::text = so.source_system::text
     JOIN edw_prod_dbo.w_sales_orders_f sof ON sof.line_id = so.line_id AND sof.source_system::text = so.source_system::text
     JOIN edw_prod_dbo.w_oper_unit_d ou ON f.org_id = ou.org_id AND f.source_system::text = ou.source_system::text
     LEFT JOIN oc_prod_dbo.hr_locations st ON f.ship_to_site_use_id::text = st.location_id::text AND f.source_system::text = 'OC'::text
     LEFT JOIN edw_prod_dbo.w_customer_d sld ON f.customer_id = sld.party_id AND f.source_system::text = sld.source_system::text
     JOIN edw_prod_dbo.w_organization_d org ON f.organization_id = org.src_org_id AND f.source_system::text = org.source_system::text
     JOIN edw_prod_dbo.w_item_org_d i ON f.inventory_item_id = i.inventory_item_id AND f.organization_id = i.organization_id AND f.source_system::text = i.source_system::text
     LEFT JOIN edw_prod_dbo."W_PRODUCT_DH_V" fh ON sof.product_code_node::text = fh.node::text
  WHERE so.order_header_type::text = 'Transfer Order'::text;