-- edw_prod_dbo.inv_daily_shipping_v source

CREATE OR REPLACE VIEW edw_prod_dbo.inv_daily_shipping_v
AS SELECT DISTINCT COALESCE(sv.confirm_date, sv.actual_ship_date::timestamp without time zone)::date AS "Confirm Date",
    sv.order_number AS "Order Number",
    sv.order_header_type AS "Order Type",
    sv.org_id AS "Org",
    sv.organization_code AS "W/H",
        CASE
            WHEN (sv.ship_date::date - sv.schedule_date) < 0 THEN 'LATE ORDER'::text
            ELSE ' '::text
        END AS "Attention",
    sv.cust_po_number AS "Customer PO",
        CASE
            WHEN sv.source_system::text = 'EBS'::text THEN concat(sv.line_number, '.', sv.shipment_number)
            ELSE concat(sv.line_number, '.', sv.fulfillment_line_number)
        END AS "Line",
    sv.delivery_detail_id AS "Delivery Detail ID",
    sv.delivery_number AS "Delivery",
    sv.order_subinventory AS "Sub Inventory",
    sv.shipped_quantity AS "Quantity Shipped",
    sv.order_currency AS "Order Currency",
    sv.standard_cost_currency AS "Report Currency",
    sv.unit_price AS "Unit Price",
    round(COALESCE(edw_prod_dbo.edw_getdailyrate(COALESCE(sv.ship_date, sv.actual_ship_date::timestamp without time zone)::date, sv.order_currency, sv.standard_cost_currency, sv.source_system, 1::double precision), 1::double precision)::numeric, 5) AS "Functional Exchange Rate",
    round((COALESCE(sv.shipped_quantity, 0::double precision) * sv.unit_price * round(edw_prod_dbo.edw_getdailyrate(COALESCE(sv.ship_date, sv.actual_ship_date::timestamp without time zone)::date, sv.order_currency, sv.standard_cost_currency, sv.source_system, 1::double precision)::numeric, 5)::double precision)::numeric, 2) AS "Functional Ext Price",
    sv.item_number AS "Internal Part Number",
        CASE
            WHEN sv.source_system::text = 'EBS'::text THEN sv.ordered_item
            ELSE COALESCE(sv.customer_pn, sv.tp_item_number, sv.ordered_item)
        END AS "Ordered Item Number",
    sv.description AS "Item Description",
    sv.product_family AS "Product Family",
    sv.product_line AS "Product Line",
    sv.product_model AS "Product Model",
    sv.commodity_class AS "Commodity Class",
    sv.category AS "Category",
    sv.sourcing_segment AS "Sourcing Segment",
    sv.planner_code AS "Planner Code",
    sv.delivery_status AS "Status",
    sv.shipping_method_code AS "Ship Method",
    sv.freight_terms_code AS "Freight Terms",
    sv.fob_code AS "Shipping Terms",
    NULL::text AS "Freight Costs",
    sv.carrier AS "Carrier",
    sv.tracking_number AS "Tracking #",
    sv.waybill AS "WayBill #",
    NULL::text AS "Additional Tracking",
    sv.order_date AS "Date Ordered",
    sv.request_date AS "Date Requested",
    sv.plan_date AS "Date Planned",
    sv.schedule_date AS "Date Scheduled",
    sv.promise_date AS "Date Promised",
    sv.st_customer_account AS "Customer Number",
    sv.st_customer_name AS "Customer Name",
    sv.st_site_number AS "Site Number",
    sv.st_site_name AS "Site Name",
    sv.st_location AS "Location",
    sv.st_city AS "City",
    sv.st_state AS "State",
    sv.st_country AS "Country",
    sv.item_creation_date AS "Item Creation Date",
    sv.serial_number AS "Serial Number(s)",
    sdc.contact_first_name AS "Sold To First Name",
    sdc.contact_last_name AS "Sold To Last Name",
    sdc.contact_email AS "Sold To Email",
    sdc.contact_phone AS "Sold To Phone",
    stc.contact_first_name AS "Ship To First Name",
    stc.contact_last_name AS "Ship To Last Name",
    stc.contact_phone AS "Ship To Phone",
    btc.contact_first_name AS "Bill To First Name",
    btc.contact_last_name AS "Bill To Last Name",
    btc.contact_phone AS "Bill To Phone",
    COALESCE(sv.ship_date, sv.actual_ship_date::timestamp without time zone)::date AS "Actual Shipment Date",
    sv.product_class AS "Item Product Class",
    sv.shipment_priority_code AS "Shipment Priority",
        CASE
            WHEN sv.planning_make_buy_code = 1::numeric THEN 'Make'::text
            ELSE 'Buy'::text
        END AS "Make / Buy",
    sv.atp_rule_name AS "ATP Rule",
    sv.full_lead_time AS "Lead Time Days",
    round(sv.full_lead_time / 7.0, 0) AS "Lead Time Weeks",
    NULL::text AS "Planning Type",
    sv.service_activity AS "Service Activity Code",
    NULL::text AS "Copy Exact",
    sv.inventory_item_status_code AS "Item Status",
    NULL::text AS "Pick Sub Inventory",
    NULL::text AS "OTD Code",
    NULL::text AS "OTD Comments",
    NULL::text AS "Planner Notes",
    NULL::text AS "OTD Part Number",
    NULL::text AS "OTD Supplier",
    NULL::text AS "Group",
    sv.unit_weight AS "Gross Weight",
    sv.weight_uom_code AS "Weight UOM",
    sv.hts_code AS "HTS Code",
    sv.country_of_origin AS "Count of Origin",
    sv.picked_date AS "Picked Date",
    COALESCE(sv.shipped_quantity, 0::double precision) * sv.unit_price * round(edw_prod_dbo.edw_getdailyrateusd(COALESCE(sv.ship_date, sv.actual_ship_date::timestamp without time zone)::date, sv.standard_cost_currency, sv.source_system, 1::double precision)::numeric, 5)::double precision AS "Ext Price USD",
    sv.ic_po_number AS "IC PO Number",
    sv.ic_po_line AS "IC PO Line",
    sv.ref_order_number AS "EBS SO Number",
    sv.ref_order_line AS "EBS SO Line",
    sv.source_system AS "Source System"
   FROM edw_prod_dbo.dm_shipping_v sv
     LEFT JOIN ( SELECT w_contacts_d.id,
            w_contacts_d.contact_id,
            w_contacts_d.cust_acct_id,
            w_contacts_d.cust_contact_id,
            w_contacts_d.constact_status,
            w_contacts_d.contact_number,
            w_contacts_d.contact_name,
            w_contacts_d.contact_last_name,
            w_contacts_d.contact_middle_name,
            w_contacts_d.contact_first_name,
            w_contacts_d.contact_language,
            w_contacts_d.contact_addr_type,
            w_contacts_d.contact_address1,
            w_contacts_d.contact_address2,
            w_contacts_d.contact_postal_code,
            w_contacts_d.contact_city,
            w_contacts_d.contact_state,
            w_contacts_d.contact_province,
            w_contacts_d.contact_country,
            w_contacts_d.contact_email,
            w_contacts_d.contact_phone,
            w_contacts_d.integration_id,
            w_contacts_d.created_date,
            w_contacts_d.updated_date,
            w_contacts_d.source_system
           FROM edw_prod_dbo.w_contacts_d
          WHERE w_contacts_d.contact_addr_type::text = 'CONTACT'::text) sdc ON sv.sold_to_contact_id = sdc.contact_id AND sv.source_system::text = sdc.source_system::text
     LEFT JOIN ( SELECT w_contacts_d.id,
            w_contacts_d.contact_id,
            w_contacts_d.cust_acct_id,
            w_contacts_d.cust_contact_id,
            w_contacts_d.constact_status,
            w_contacts_d.contact_number,
            w_contacts_d.contact_name,
            w_contacts_d.contact_last_name,
            w_contacts_d.contact_middle_name,
            w_contacts_d.contact_first_name,
            w_contacts_d.contact_language,
            w_contacts_d.contact_addr_type,
            w_contacts_d.contact_address1,
            w_contacts_d.contact_address2,
            w_contacts_d.contact_postal_code,
            w_contacts_d.contact_city,
            w_contacts_d.contact_state,
            w_contacts_d.contact_province,
            w_contacts_d.contact_country,
            w_contacts_d.contact_email,
            w_contacts_d.contact_phone,
            w_contacts_d.integration_id,
            w_contacts_d.created_date,
            w_contacts_d.updated_date,
            w_contacts_d.source_system
           FROM edw_prod_dbo.w_contacts_d
          WHERE w_contacts_d.contact_addr_type::text = 'CONTACT'::text) stc ON sv.ship_to_contact_id = stc.contact_id AND sv.source_system::text = stc.source_system::text
     LEFT JOIN ( SELECT w_contacts_d.id,
            w_contacts_d.contact_id,
            w_contacts_d.cust_acct_id,
            w_contacts_d.cust_contact_id,
            w_contacts_d.constact_status,
            w_contacts_d.contact_number,
            w_contacts_d.contact_name,
            w_contacts_d.contact_last_name,
            w_contacts_d.contact_middle_name,
            w_contacts_d.contact_first_name,
            w_contacts_d.contact_language,
            w_contacts_d.contact_addr_type,
            w_contacts_d.contact_address1,
            w_contacts_d.contact_address2,
            w_contacts_d.contact_postal_code,
            w_contacts_d.contact_city,
            w_contacts_d.contact_state,
            w_contacts_d.contact_province,
            w_contacts_d.contact_country,
            w_contacts_d.contact_email,
            w_contacts_d.contact_phone,
            w_contacts_d.integration_id,
            w_contacts_d.created_date,
            w_contacts_d.updated_date,
            w_contacts_d.source_system
           FROM edw_prod_dbo.w_contacts_d
          WHERE w_contacts_d.contact_addr_type::text = 'CONTACT'::text) btc ON sv.bill_to_contact_id = btc.contact_id AND sv.source_system::text = btc.source_system::text
  WHERE sv.cancelled_flag <> 'Y'::bpchar AND upper(sv.delivery_status::text) = 'SHIPPED'::text AND COALESCE(sv.organization_code, ' '::character varying)::text !~~ 'X%'::text;