use DataWarehouse


--Explore all object in a database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

--EXPLORE ALL COLUMN IN A TABLE
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='fact_sales_v';

--EXPLORE all country our customers come from

SELECT distinct country FROM DataWarehouse.gold.dim_customers_v

--explore all categories the major devision
SELECT distinct category,subcategory, product_name FROM DataWarehouse.gold.dim_products_v
order by 1,2,3

-- find the date of first and last order
-- how many years of sales available
SELECT
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) AS Total_year_range
FROM DataWarehouse.gold.fact_sales_v

--Find the youngest and oldest customer
SELECT
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year,MIN(birthdate),GETDATE()) AS  oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year,MAX(birthdate),GETDATE()) AS  youngest_age
FROM DataWarehouse.gold.dim_customers_v

--Find the total sales
SELECT SUM(sales_amount) AS total_sales
FROM DataWarehouse.gold.fact_sales_v

--Find how many items are sold
SELECT SUM(quantity) AS total_quantity
FROM DataWarehouse.gold.fact_sales_v

-- find the avg sailing price
SELECT avg(price) AS avg_price
FROM DataWarehouse.gold.fact_sales_v
--Find the total number of orders
SELECT count(order_number) AS total_orders
FROM DataWarehouse.gold.fact_sales_v

SELECT count(distinct order_number) AS total_orders
FROM DataWarehouse.gold.fact_sales_v

-----------------------------------MAgnitude analysys------------------------------

--find the total number of products
SELECT count(product_number) total_product FROM DataWarehouse.gold.dim_products_v

-- find the total number of customers that has placed the order
SELECT count(distinct dcv.customer_key) AS total_customer
FROM DataWarehouse.gold.dim_customers_v dcv
INNER JOIN DataWarehouse.gold.fact_sales_v fsv
ON dcv.customer_key = fsv.customer_key

--find the total customers by countries
SELECT country,COUNT(customer_id) AS Total_customer_country_wise
FROM DataWarehouse.gold.dim_customers_v group by country order by Total_customer_country_wise DESC 
--find total customer by gender
SELECT gender,COUNT(customer_id) AS Total_customer_cgender_wise
FROM DataWarehouse.gold.dim_customers_v group by gender order by Total_customer_cgender_wise DESC 
--find total products by category
SELECT category, count(product_number) total_product_category_wise 
FROM DataWarehouse.gold.dim_products_v group by category order by total_product_category_wise DESC 
--what is the average costs in each category
SELECT category, AVG(COALESCE(cost,0)) avg_cost_category_wise 
FROM DataWarehouse.gold.dim_products_v group by category order by avg_cost_category_wise DESC 
--what is the total revenue generated by each category
SELECT 
dpv.category,
SUM(fsv.sales_amount) AS Total_revenue
FROM DataWarehouse.gold.fact_sales_v fsv
LEFT JOIN DataWarehouse.gold.dim_products_v dpv
ON fsv.product_key = dpv.product_key
group by dpv.category ORDER BY Total_revenue DESC
--find total revenue is generated by each customer
SELECT 
dcv.customer_id,
dcv.first_name,
dcv.last_name,
SUM(fsv.sales_amount) AS Total_revenue
FROM DataWarehouse.gold.fact_sales_v fsv
LEFT JOIN DataWarehouse.gold.dim_customers_v  dcv
ON fsv.customer_key= dcv.customer_key
group by dcv.customer_id,dcv.first_name,dcv.last_name
ORDER BY Total_revenue DESC
--what is the distributuin of sold items accross countries
SELECT
dcv.country,
SUM(fsv.quantity) AS sum_quantity
FROM DataWarehouse.gold.fact_sales_v fsv
LEFT JOIN DataWarehouse.gold.dim_customers_v  dcv
ON fsv.customer_key= dcv.customer_key
group by dcv.country ORDER BY sum_quantity DESC

-------------------------------------------RANK ANALYSIS----------